title:             Aman's Blog
email:             aman.iitk072@gmail.com
description:       A collection of the articles I wrote about several of my Life Experiences, Creations, Travel Guides, and Projects.
author:            Aman Abhishek Tiwari
baseurl:           ""
url:               "http://amanabt.github.io"
logo:              "/img/logo.png"

# Social Profiles

github_username:   amanabt
facebook_username: aman.iitk072
linkedin_username: aman2official

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
